name: paylike_dart_client
description: Higher level API client for Paylike.io to provide a handy interface for constructing requests towards paylike.io
version: 1.0.7
homepage: https://paylike.io
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  build_runner: ^2.1.0
  mockito: ^5.0.13
  pedantic: ^1.10.0
  shelf: ^1.2.0
  test: ^1.16.0
dependencies: 
  paylike_dart_request: ^1.0.9
